- hosts: all
  gather_facts: yes
  become: true
  vars:
    region: us-west-2
  tasks:
    - shell: curl http://169.254.169.254/latest/meta-data/placement/availability-zone
      register: availability_zone
    - name: get availability zone
      shell: curl http://169.254.169.254/latest/meta-data/instance-id
      register: instance_id
    - name: tag instance
      shell: aws ec2 create-tags --resources {{ instance_id.stdout }} --tags Key=Name,Value=bastion-{{ availability_zone.stdout }} Key=hostname,Value=bastion-{{ availability_zone.stdout }} --region {{ region }}
    - name: set hostname
      hostname: name="bastion-{{ availability_zone.stdout }}"
    - name: add hostname to /etc/hosts
      lineinfile:
        dest: "/etc/hosts"
        state: present
        regexp: "^127.0.0.1 localhost"
        line: "127.0.0.1 localhost bastion-{{ availability_zone.stdout }}"
